# Generated by Django 4.2 on 2023-09-17 10:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from routine.fields import CustomModels


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Minicomment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True, null=True), size=None
                    ),
                ),
                ("goal_id", models.IntegerField(blank=True, default=0)),
                ("dow", CustomModels.DOWField()),
                (
                    "start_time",
                    CustomModels.TimeStringField(
                        default="000000+0000", max_length=15
                    ),
                ),
                (
                    "end_time",
                    CustomModels.TimeStringField(
                        default="000000+0000", max_length=15
                    ),
                ),
                ("title", models.CharField(max_length=15)),
                ("subtitle", models.CharField(blank=True, max_length=40)),
                ("icon", models.CharField(blank=True, max_length=1)),
                ("is_published", models.BooleanField(default=False, help_text="公開設定")),
                ("is_notified", models.BooleanField(default=False, help_text="通知設定")),
                ("bookmark_num", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("detail", models.CharField(blank=True, max_length=60)),
                ("icon", models.CharField(blank=True, max_length=1)),
                ("required_time", models.IntegerField()),
                ("is_notified", models.BooleanField(default=False, help_text="通知設定")),
                (
                    "routine_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine.routine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_achieved", models.BooleanField(default=True, help_text="完了したか")),
                ("done_time", models.IntegerField()),
                ("when", models.DateTimeField(help_text="完了日時")),
                ("bookmark_num", models.IntegerField(default=0)),
                (
                    "routine_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine.routine",
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="routine.task"
                    ),
                ),
            ],
        ),
    ]
