# Generated by Django 4.2.1 on 2023-06-17 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.CharField(max_length=90)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterestCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.CharField(max_length=90)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=15)),
                (
                    "interest_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="routine.interest",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("detail", models.CharField(blank=True, max_length=60)),
                ("icon", models.CharField(blank=True, max_length=1)),
                ("required_time", models.IntegerField()),
                (
                    "routine_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine.routine",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="nosqlbase_ptr",
        ),
        migrations.AddField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="NoSQLBase",
        ),
        migrations.AddField(
            model_name="interest",
            name="interest_cluster_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="routine.interestcluster",
            ),
        ),
    ]
