# Generated by Django 4.2 on 2023-08-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("routine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskcomment",
            name="task_id",
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="task_record_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="routine.taskrecord",
            ),
            preserve_default=False,
        ),
    ]
