# Generated by Django 4.2 on 2023-10-03 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("routine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="minicomment",
            name="task_finish_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="routine.taskfinish"
            ),
        ),
    ]
