# Generated by Django 4.2 on 2023-11-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routinefinish",
            name="is_achieved",
            field=models.BooleanField(default=True),
        ),
    ]
