# Generated by Django 4.2 on 2023-09-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routine", "0002_remove_taskcomment_task_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskComment",
            new_name="Minicomment",
        ),
        migrations.DeleteModel(
            name="test",
        ),
        migrations.AlterField(
            model_name="taskrecord",
            name="is_achieved",
            field=models.BooleanField(default=True, help_text="完了したか"),
        ),
        migrations.AlterField(
            model_name="taskrecord",
            name="when",
            field=models.DateTimeField(help_text="完了日時"),
        ),
    ]
