# Generated by Django 4.2 on 2023-11-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routinefinish",
            name="share",
            field=models.BooleanField(default=True),
        ),
    ]
