# Generated by Django 4.2 on 2023-10-12 10:53

from django.db import migrations
from routine.fields import CustomModels


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="end_time",
            field=CustomModels.TimeStringField(
                default="000000+0000", max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="routine",
            name="start_time",
            field=CustomModels.TimeStringField(
                default="000000+0000", max_length=15
            ),
        ),
    ]
