# Generated by Django 4.2 on 2023-11-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="tag_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="routine.tag",
            ),
        ),
    ]
