# Generated by Django 4.2 on 2023-11-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0003_alter_routinefinish_is_achieved"),
    ]

    operations = [
        migrations.AddField(
            model_name="routinefinish",
            name="share",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="routinefinish",
            name="is_achieved",
            field=models.BooleanField(default=True, help_text="完了したか"),
        ),
    ]
