# Generated by Django 4.2 on 2023-10-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
