# Generated by Django 4.2 on 2023-11-11 06:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tag_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(null=True), null=True, size=None
            ),
        ),
    ]
