# Generated by Django 4.2 on 2023-10-12 00:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="user",
            name="is_hot_user",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="job",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_media_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="self_introduction",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tag_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(null=True), default=1, size=None
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
