# Generated by Django 4.2 on 2023-10-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_auth", "0002_user_follower_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="follower",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
