# Generated by Django 4.2 on 2023-10-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_auth", "0003_alter_user_follower_alter_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="follower",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.IntegerField(default=0),
        ),
    ]
