# Generated by Django 4.2 on 2023-09-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedpost",
            name="bookmark_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="feedpost",
            name="like_num",
            field=models.IntegerField(default=0),
        ),
    ]
