# Generated by Django 4.2 on 2023-10-12 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedpost",
            name="post_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 12, 11, 19, 32, 55158, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="feedpostcomment",
            name="post_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 12, 11, 19, 32, 55158, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="taskfinishcomment",
            name="post_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 12, 11, 19, 32, 55158, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
