# Generated by Django 4.2 on 2023-11-21 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feed", "0001_initial"),
        ("routine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routinefinishcomment",
            name="routine_finish_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="routine.routinefinish"
            ),
        ),
        migrations.AddField(
            model_name="feedpostcomment",
            name="feed_post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feed.feedpost"
            ),
        ),
        migrations.AddField(
            model_name="feedpost",
            name="tag_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="routine.tag",
            ),
        ),
    ]
