# Generated by Django 4.2 on 2023-11-04 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("routine", "0001_initial"),
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskfinishcomment",
            name="task_finish_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="routine.taskfinish"
            ),
        ),
        migrations.AddField(
            model_name="feedpostcomment",
            name="feed_post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="feed.feedpost"
            ),
        ),
        migrations.AddField(
            model_name="feedpost",
            name="challenge_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feed.challenge",
            ),
        ),
    ]
