# Generated by Django 4.2 on 2023-10-12 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_alter_feedpost_post_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedpost",
            name="post_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 12, 11, 20, 5, 331584, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="feedpostcomment",
            name="post_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 12, 11, 20, 5, 332580, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="taskfinishcomment",
            name="post_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 12, 11, 20, 5, 334155, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
