# Generated by Django 4.2 on 2023-10-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
