# Generated by Django 4.2 on 2023-10-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="feedpost",
            table="feed_post",
        ),
    ]
