# Generated by Django 4.2 on 2023-09-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplyAuth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.IntegerField(default=0),
        ),
    ]
